//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace tckimlik.TCKimlikNoDogrulama {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="KPSPublicSoap", Namespace="http://tckimlik.nvi.gov.tr/WS")]
    public partial class KPSPublic : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TCKimlikNoDogrulaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public KPSPublic() {
            this.Url = global::tckimlik.Properties.Settings.Default.tckimlik_TCKimlikNoDogrulama_KPSPublic;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TCKimlikNoDogrulaCompletedEventHandler TCKimlikNoDogrulaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tckimlik.nvi.gov.tr/WS/TCKimlikNoDogrula", RequestNamespace="http://tckimlik.nvi.gov.tr/WS", ResponseNamespace="http://tckimlik.nvi.gov.tr/WS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool TCKimlikNoDogrula(long TCKimlikNo, string Ad, string Soyad, int DogumYili) {
            object[] results = this.Invoke("TCKimlikNoDogrula", new object[] {
                        TCKimlikNo,
                        Ad,
                        Soyad,
                        DogumYili});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void TCKimlikNoDogrulaAsync(long TCKimlikNo, string Ad, string Soyad, int DogumYili) {
            this.TCKimlikNoDogrulaAsync(TCKimlikNo, Ad, Soyad, DogumYili, null);
        }
        
        /// <remarks/>
        public void TCKimlikNoDogrulaAsync(long TCKimlikNo, string Ad, string Soyad, int DogumYili, object userState) {
            if ((this.TCKimlikNoDogrulaOperationCompleted == null)) {
                this.TCKimlikNoDogrulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTCKimlikNoDogrulaOperationCompleted);
            }
            this.InvokeAsync("TCKimlikNoDogrula", new object[] {
                        TCKimlikNo,
                        Ad,
                        Soyad,
                        DogumYili}, this.TCKimlikNoDogrulaOperationCompleted, userState);
        }
        
        private void OnTCKimlikNoDogrulaOperationCompleted(object arg) {
            if ((this.TCKimlikNoDogrulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TCKimlikNoDogrulaCompleted(this, new TCKimlikNoDogrulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void TCKimlikNoDogrulaCompletedEventHandler(object sender, TCKimlikNoDogrulaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TCKimlikNoDogrulaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TCKimlikNoDogrulaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591